blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<year>[0-9]{4})/(?P<month>[-\w]+)/(?P<day>[0-9]+)/(?P<slug>.+)/$',
        views.PostDetailView.as_view(), name="detail"),
    url(r'^category/(?P<slug>.+)/$', views.InCategoryView.as_view(), name='in_category'),
    url(r'^tag/(?P<slug>.+)/$', views.InTagView.as_view(), name='in_tag'),
    url(r'^search/$', views.SearchView.as_view(), name='search'),
    url(r'^archive/(?P<year>[0-9]{4})/$', views.PostYearArchiveView.as_view(), name='archive_year'),
    url(r'^archive/(?P<year>[0-9]{4})/(?P<month>[0-9]+)/$', views.PostMonthArchiveView.as_view(),
        name="archive_month"),
    # url(r'^messages/$', views.MessageBoardView.as_view(), name='message_board'),
    # url(r'^messages/(?P<slug>.+)/$', views.AnnouncementDetailView.as_view(), name='announcement'),
    # url(r'^contact/$', views.ContactView.as_view(), name='contact'),
]

config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap

from blog.models import Post

info_dict = {
    'queryset': Post.objects.all(),
    'date_field': 'modified',
}


urlpatterns = [
    url(r'', include('blog.urls', namespace='blog')),
    url(r'^admin/', admin.site.urls),
    url(r'^comment/', include('django_comments.urls')),
    url(r'^comment/', include('comments.urls', namespace='comments')),
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'blog': GenericSitemap(info_dict, priority=0.6)}},
        name='django.contrib.sitemaps.views.sitemap'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from datetime import datetime

from django.db import models
from django.db.models.functions import TruncMonth
from django.db.models import DateTimeField, F, Count
from django.utils.translation import ugettext_lazy as _
from django.utils.html import mark_safe

from django.contrib.contenttypes.fields import GenericRelation
from django.core.urlresolvers import reverse
from django.conf import settings

from model_utils import Choices
from model_utils.fields import SplitField, MonitorField
from model_utils.models import TimeStampedModel, StatusModel, TimeFramedModel, SoftDeletableModel
from autoslug import AutoSlugField
from taggit.managers import TaggableManager
from markdownx.utils import markdownify
from mptt.models import MPTTModel

from comments.models import MyComment


class PostManager(models.Manager):
    def archive(self):
        return self.annotate(
            dates=TruncMonth('pub_date', output_field=DateTimeField())
        ).values('dates').annotate(post_count=Count('id')).order_by('-dates')


class Post(StatusModel, TimeStampedModel, TimeFramedModel):
    objects = PostManager()

    STATUS = Choices(
        ('draft', _('draft')),
        ('published', _('published')),
        ('hidden', _('hidden')),
    )

    title = models.CharField(_('title'), max_length=255)
    body = SplitField(_('body'))
    pub_date = MonitorField(_('published date/time'), monitor='status', when=['published'])
    slug = AutoSlugField(populate_from='title', max_length=255, allow_unicode=True, unique_for_date='pub_date')
    featured = models.BooleanField(_('featured'), default=False)
    views = models.PositiveIntegerField(_('views'), default=0)
    lead = models.TextField(_('lead'), blank=True)
    comment_enabled = models.BooleanField(_('comments enabled'), default=True)

    cover = models.ForeignKey('covers.Cover', verbose_name=_('cover'), blank=True, null=True, on_delete=models.SET_NULL)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('author'))
    category = models.ForeignKey('categories.Category', verbose_name='category')

    tags = TaggableManager(blank=True)
    comments = GenericRelation(MyComment, object_id_field='object_pk', content_type_field='content_type')

    class Meta:
        ordering = ('-pub_date',)
        get_latest_by = 'pub_date'
        verbose_name = _('Post')
        verbose_name_plural = _('Posts')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.cover = self.cover or self.category.cover
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={
            'year': self.pub_date.strftime('%Y'),
            'month': self.pub_date.strftime('%m'),
            'day': self.pub_date.strftime('%d'),
            'slug': self.slug,
        })

    @property
    def body_html(self):
        return mark_safe(markdownify(self.body.content))

    @property
    def excerpt_html(self):
        return mark_safe(markdownify(self.body.excerpt))

    @property
    def lead_html(self):
        return mark_safe(markdownify(self.lead))

    def root_comments(self):
        return self.comments.filter(parent__isnull=True)

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

blog/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.core.mail import mail_admins

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div, Layout, HTML


class ContactForm(forms.Form):
    name = forms.CharField(max_length=125)
    email = forms.EmailField()
    subject = forms.CharField(max_length=255)
    message = forms.CharField(widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_action = 'blog:contact'
        self.helper.layout = Layout(
            Div(
                Div(
                    'name', css_class='col-md-6'
                ),
                Div(
                    'email', css_class='col-md-6'
                ),
                Div(
                    'subject', css_class='col-md-12'
                ),

                Div(
                    'message', css_class='col-md-12'
                ),
                HTML(
                    """
                    <div class="col-xs-12 col-md-12 form-group">
                        <button class="btn btn-info pull-right" type="submit"><i class="fa fa-paper-plane-o"
                                                                                 aria-hidden="true"></i>
                            Submit
                        </button>
                    </div>
                    """
                ),
                css_class='row'
            )
        )
        self.fields['message'].widget.attrs['rows'] = 6
        self.fields['name'].widget.attrs['placeholder'] = _('name')
        self.fields['email'].widget.attrs['placeholder'] = _('email')
        self.fields['subject'].widget.attrs['placeholder'] = _('subject')
        self.fields['message'].widget.attrs['placeholder'] = _('message')

    def send(self):
        mail_admins(
            subject=self.cleaned_data.get('subject'),
            message=self.cleaned_data.get('message')
        )

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import (ListView, DateDetailView, TemplateView, FormView,
                                  DetailView, YearArchiveView, MonthArchiveView)
from django.utils.html import mark_safe
from django.core.urlresolvers import reverse

from braces.views import MessageMixin, FormValidMessageMixin, SetHeadlineMixin
from taggit.models import Tag
from haystack.generic_views import SearchView as HaystackSearchView

from categories.models import Category

from .models import Post
from .forms import ContactForm


class IndexView(ListView):
    paginate_by = 10
    model = Post
    template_name = "blog/index.html"


class PostYearArchiveView(SetHeadlineMixin, YearArchiveView):
    paginate_by = 10
    queryset = Post.objects.all()
    date_field = "pub_date"
    make_object_list = True
    context_object_name = 'post_list'
    template_name = 'blog/post_list.html'
    headline = '文章归档_追梦人物的博客'


class PostMonthArchiveView(SetHeadlineMixin, MonthArchiveView):
    paginate_by = 10
    queryset = Post.objects.all()
    date_field = "pub_date"
    context_object_name = 'post_list'
    template_name = 'blog/post_list.html'
    month_format = '%m'
    headline = '文章归档_追梦人物的博客'


class PostDetailView(DateDetailView):
    model = Post
    date_field = "pub_date"
    month_format = '%m'
    template_name = 'blog/detail.html'

    def get(self, request, *args, **kwargs):
        response = super(PostDetailView, self).get(request, *args, **kwargs)
        self.object.increase_views()
        return response


class InCategoryView(MessageMixin, SetHeadlineMixin, ListView):
    paginate_by = 10
    model = Post
    template_name = "blog/post_list.html"

    def get_queryset(self):
        c = get_object_or_404(Category, slug=self.kwargs.get('slug'))
        posts = Post.published.filter(category=c)
        self.messages.info(
            mark_safe("分类 <strong>{0}</strong>，{1} 篇文章".format(c.name, posts.count())))
        return posts

    def get_headline(self):
        c = get_object_or_404(Category, slug=self.kwargs.get('slug'))
        return "%s_追梦人物的博客" % c.name


class InTagView(SetHeadlineMixin, MessageMixin, ListView):
    paginate_by = 10
    model = Post
    template_name = "blog/post_list.html"

    def get_queryset(self):
        t = get_object_or_404(Tag, slug=self.kwargs.get('slug'))
        posts = Post.published.filter(tags=t)
        self.messages.info(
            mark_safe("标签 <strong>{0}</strong>，{1} 篇文章".format(t.name, posts.count())))
        return posts

    def get_headline(self):
        t = get_object_or_404(Tag, slug=self.kwargs.get('slug'))
        return "%s_追梦人物的博客" % t.name


# class MessageBoardView(ListView):
#     model = Announcement
#     template_name = 'blog/messages_board.html'
#
#     def get_context_data(self, **kwargs):
#         kwargs = super(MessageBoardView, self).get_context_data(**kwargs)
#         try:
#             announcement = Announcement.objects.latest()
#         except Announcement.DoesNotExist:
#             announcement = None
#         kwargs.update({'announcement': announcement})
#         return kwargs
#
#
# class AnnouncementDetailView(DetailView):
#     model = Announcement
#     template_name = 'blog/messages_board.html'
#
#     def get_context_data(self, **kwargs):
#         kwargs = super(AnnouncementDetailView, self).get_context_data(**kwargs)
#         announcement_list = Announcement.objects.all()
#         kwargs.update({'announcement_list': announcement_list})
#         return kwargs


class ContactView(FormValidMessageMixin, FormView):
    form_valid_message = 'Thank you for you message'
    form_class = ContactForm
    template_name = 'blog/contact.html'

    def form_valid(self, form):
        form.send()
        return super(ContactView, self).form_valid(form)

    def get_success_url(self):
        self.success_url = reverse('blog:contact')
        return super().get_success_url()


class SearchView(MessageMixin, HaystackSearchView):
    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)

        if self.queryset:
            self.messages.success(
                mark_safe(
                    'There are {0} post found in keyword <strong>{1}</strong>'
                        .format(self.queryset.count(), response.context_data['form'].cleaned_data.get('q'))
                )
            )
        return response

templates/blog/_col1.html
<div class="col-md-12">
    <div class="post-img">
        <a href="{{ post.get_absolute_url }}">
            <img src="{% if post.cover %}{{ post.cover.cover_770_300.url }}{% else %}
                                             {{ post.category.cover.cover_770_300.url }}{% endif %}"
                 alt="Review Image"/>
        </a>
        <a href="#" class="post-tag">{{ post.category }}</a>
        <div class="post-info">
            <p>
                                            <span class="post-date">
                                            <a href="#">{{ post.pub_date | date:'Y-m-d' }}</a>
                                            </span>
                <span class="post-comments">
                    <a href="{{ post.get_absolute_url }}#comment-area" class="ds-thread-count"
                       data-thread-key="{{ post.pk }}">
                    </a>
                </span>
                <span class="post-social-links">
														<a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a>
                                            </span>
            </p>
        </div>
    </div>
    <div class="post-content">
        <h6 class="post-title">
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h6>
        <div class="post-short-desc">
            {% if post.lead %}
                {{ post.lead_html | truncatechars_html:200 }}
            {% else %}
                {{ post.excerpt_html | truncatechars_html:200 }}
            {% endif %}
        </div>
        <a href="{{ post.get_absolute_url }}" class="continue-link">继续阅读...</a>
    </div>
</div>

templates/blog/_col2.html
<div class="col-md-6 col-sm-6">
    <div class="post-img">
        <a href="{{ post.get_absolute_url }}">
            <img src="{% if post.cover %}
                            {{ post.cover.cover_370_230.url }}
                        {% else %}
                            {{ post.category.cover.cover_370_230.url }}
                        {% endif %}"
                 alt="Popular Post"/>
        </a>
        <a href="{% url 'blog:in_category' post.category.slug %}"
           class="post-tag">
            {{ post.category }}
        </a>
        <div class="post-info">
            <p>
                <span class="post-date">
                    <a href="{{ post.get_absolute_url }}">{{ post.pub_date | date:'Y-m-d' }}</a>
                </span>
                <span class="post-comments">
                    <a href="{{ post.get_absolute_url }}#comment-area" class="ds-thread-count"
                       data-thread-key="{{ post.pk }}">
                    </a>
                </span>
                <span class="post-social-links">
                    <a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a>
                </span>
            </p>
        </div>
    </div>
    <div class="post-content">
        <h6 class="post-title">
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h6>
        <div class="post-short-desc">
            {% if post.lead %}
                {{ post.lead_html | truncatechars_html:200 }}
            {% else %}
                {{ post.excerpt_html | truncatechars_html:200 }}
            {% endif %}
        </div>
        <a href="{{ post.get_absolute_url }}"
           class="continue-link">继续阅读...</a>
    </div>
</div>

templates/blog/_pagination.html
{% load bootstrap_pagination %}

{% if post_list %}
    {% bootstrap_paginate page_obj range=10 show_first_last='true' size='small' %}
{% endif %}

templates/blog/_post_list.html
<div class="row">
    {% for post in post_list %}
        {% include 'blog/_col1.html' %}
    {% empty %}
        暂无文章
    {% endfor %}
</div>

templates/blog/detail.html
{% extends 'base.html' %}
{% block title %}
    <title>{{ post.title }}_{{ post.category }}_追梦人物的博客</title>
{% endblock title %}
{% block main %}
    <!-- single-blog-area start -->
    <div class="col-md-8 col-sm-12">
        <div class="single-blog-details">
            <span class="tag"><a href="{% url 'blog:in_category' post.category.slug %}">{{ post.category }}</a></span>
            <h1 class="post-title">{{ post.title }}</h1>
            <p class="post-date">发表于 {{ post.pub_date|date }}</p>
            <div class="post-long-desc">
                {% if post.lead %}
                    <blockquote>
                        {{ post.lead_html }}
                    </blockquote>
                {% endif %}
                {{ post.body_html }}
            </div>
            <div class="single-blog-bottom fix">
                <div class="post-social-links pull-left">
                    <p>
                        <span class="lbl">分享到&nbsp;&nbsp;-</span>
                        <span>
                            <a href="#"><i class="fa fa-weibo" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-weixin" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-qq" aria-hidden="true"></i></a>
                        </span>
                    </p>
                </div>
                <div class="post-tags pull-right">
                    <p>
                        <span class="lbl">标签&nbsp;&nbsp;-</span>
                        <span>
                            {% for tag in post.tags.all %}
                                <a href="{% url 'blog:in_tag' tag.slug %}" title="" class="">{{ tag.name }}
                                    {% if not forloop.last %}、{% endif %}</a>
                            {% empty %}
                                暂无标签
                            {% endfor %}
                        </span>
                    </p>
                </div>
            </div>
            <hr>
            <div class="" id="comment-area">
                <!-- 多说评论框 start -->
                <div class="ds-thread" data-thread-key="{{ post.pk }}" data-title="{{ post.title }}"
                     data-url="{{ post.get_absolute_url }}"></div>
                <!-- 多说评论框 end -->
            </div><!-- /.comments-area -->
        </div><!-- /.single-blog-details -->
    </div>


    <!-- single-blog-area end -->
{% endblock main %}

templates/blog/index.html
{% extends 'base.html' %}

{% load bootstrap_pagination %}

{% block main %}
    <div class="col-md-8 col-sm-12">
        {% block post_list %}
            <div class="row">
                {% for post in post_list %}
                    {% if forloop.counter <= 4 %}
                        {% include 'blog/_col2.html' %}
                    {% else %}
                        {% include 'blog/_col1.html' %}
                    {% endif %}
                {% empty %}
                    暂无文章
                {% endfor %}
            </div>
        {% endblock post_list %}
        {% block pagination %}
            {% include 'blog/_pagination.html' %}
        {% endblock pagination %}
    </div>
{% endblock main %}

templates/blog/post_list.html
{% extends 'blog/index.html' %}

{% load bootstrap_pagination %}

{% block title %}<title>{{ headline }}</title>{% endblock title %}
{% block post_list %}
    {% include 'blog/_post_list.html' %}
{% endblock post_list %}

templates/blog/sidebar.html
{% load blog_tags %}

<div class="col-md-4 col-md-offset-0 col-sm-8 col-sm-offset-2">
    <div class="sidebar-area fix">
        <div class="single-sidebar-widget">
            <h6 class="widget-title">分类</h6>
            <div class="sidebar-content">
                <div class="categories-list">
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                            <li>
                                <a href="{% url 'blog:in_category' category.slug %}">
                                    <span class="category">{{ category }}</span>
                                    <span class="number">({{ category.post_count }})</span>
                                </a>
                            </li>
                        {% empty %}
                            暂无分类
                        {% endfor %}
                    </ul>
                </div>
            </div><!-- /.sidebar-content -->
        </div><!-- /.single-sidebar-widget -->
        <div class="single-sidebar-widget">
            <h6 class="widget-title">标签云</h6>
            <div class="sidebar-content">
                <div class="tags-list">
                    {% get_tags as tag_list %}
                    <ul>
                        {% for tag in tag_list %}
                            <li><a href="{% url 'blog:in_tag' tag.slug %}">{{ tag }}</a></li>
                        {% empty %}
                            暂无标签
                        {% endfor %}
                    </ul>
                </div>
            </div><!-- /.sidebar-content -->
        </div><!-- /.single-sidebar-widget -->
        <div class="single-sidebar-widget">
            <h6 class="widget-title">归档</h6>
            {% get_archive as archives %}
            {% regroup archives by dates.year as archives_by_year %}
            <div class="sidebar-content">
                <div class="archive-list">
                    <ul>
                        {% for archive in archives_by_year %}
                            <li><a href="{% url 'blog:archive_year' archive.grouper %}">
                                <span class="year">{{ archive.grouper }} 年</span></a>
                                <ul class="month-list">
                                    {% for month in archive.list %}
                                        <li>
                                            <a href="{% url 'blog:archive_month' archive.grouper month.dates|date:'m' %}">
                                                <span class="month">{{ month.dates |date:'n' }} 月</span><span
                                                    class="number">({{ month.post_count }})</span></a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div><!-- /.sidebar-content -->
        </div><!-- /.single-sidebar-widget -->
    </div><!-- /.sidebar-area -->
</div>