blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<year>[0-9]{4})/(?P<month>[-\w]+)/(?P<day>[0-9]+)/(?P<slug>.+)/$',
        views.PostDetailView.as_view(), name="detail"),
    url(r'^category/(?P<slug>.+)/$', views.InCategoryView.as_view(), name='in_category'),
    url(r'^tag/(?P<slug>.+)/$', views.InTagView.as_view(), name='in_tag'),
    url(r'^search/$', views.SearchView.as_view(), name='search'),
    url(r'^archive/(?P<year>[0-9]{4})/$', views.PostYearArchiveView.as_view(), name='archive_year'),
    url(r'^archive/(?P<year>[0-9]{4})/(?P<month>[0-9]+)/$', views.PostMonthArchiveView.as_view(),
        name="archive_month"),
    # url(r'^messages/$', views.MessageBoardView.as_view(), name='message_board'),
    # url(r'^messages/(?P<slug>.+)/$', views.AnnouncementDetailView.as_view(), name='announcement'),
    # url(r'^contact/$', views.ContactView.as_view(), name='contact'),
]

config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap

from blog.models import Post

info_dict = {
    'queryset': Post.objects.all(),
    'date_field': 'modified',
}


urlpatterns = [
    url(r'', include('blog.urls', namespace='blog')),
    url(r'^admin/', admin.site.urls),
    url(r'^comment/', include('django_comments.urls')),
    url(r'^comment/', include('comments.urls', namespace='comments')),
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'blog': GenericSitemap(info_dict, priority=0.6)}},
        name='django.contrib.sitemaps.views.sitemap'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html class="no-js" lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    {% block title %}
        <title>{{ headline|default:"追梦人物的博客 - 探索 Python、分享 Python" }}</title>
    {% endblock title %}
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="baidu-site-verification" content="BB0a0qDxyr"/>
    <meta name="robots" content="follow, all"/>
    <meta name="description" content="探索 Python 世界，分享 django web开发、Python 数据分析、Python 网络爬虫等一切与 Python 相关的知识"/>
    <!-- favicon
    ============================================ -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.ico">

    <!-- Google Fonts
    ============================================ -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>

    <!-- Bootstrap CSS
    ============================================ -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <!-- font-awesome CSS
    ============================================ -->
    <link rel="stylesheet" href="{% static 'blog/css/font-awesome.min.css' %}">
    <!-- owl.carousel CSS
    ============================================ -->
    <link rel="stylesheet" href="{% static 'blog/css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/owl.theme.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/owl.transitions.css' %}">
    <!-- meanmenu CSS
    ============================================ -->
    <link rel="stylesheet" href="{% static 'blog/css/meanmenu.css' %}">
    <!-- normalize CSS
    ============================================ -->
    <link rel="stylesheet" href="{% static 'blog/css/normalize.css' %}">
    <!-- main CSS
    ============================================ -->
    <link rel="stylesheet" href="{% static 'blog/css/main.css' %}">
    <!-- style CSS
    ============================================ -->
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <!-- code highlight CSS
        ============================================ -->
    <link href="{% static 'blog/css/github.css' %}" rel="stylesheet">
    <!-- responsive CSS
    ============================================ -->
    <link rel="stylesheet" href="{% static 'blog/css/responsive.css' %}">
    <!-- modernizr JS
    ============================================ -->
    {% block link %}
    {% endblock link %}
    {% block style %}
    {% endblock style %}
    <script src="{% static 'blog/js/vendor/modernizr-2.8.3.min.js' %}"></script>
</head>
<body class="home-2">
<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade
    your browser</a> to improve your experience.</p>
<![endif]-->

<!-- header-area start -->
<header id="header" class="header-area">
    <div class="header-top">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-6">
                    <div class="header-top-left">
                        <ul class="social-icons">
                            <li><a href="https://github.com/zmrenwu"><i class="fa fa-github" aria-hidden="true"></i></a>
                            </li>
                            <li><a href="http://weibo.com/u/2494998151"><i class="fa fa-weibo"
                                                                           aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-6">
                    <div class="header-top-right fix">
                        <div class="header-search">
                            <form action="#" method="post">
                                <button type="button" class="search-toggler"><i class="fa fa-search"></i></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- /.header-top -->
    <div class="header-bottom">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <div class="logo">
                        <a href="{% url 'blog:index' %}">
                            <img src="{% static 'blog/img/logo.png' %}" alt="Logo"/>
                        </a>
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="main-menu">
                        <nav>
                            <ul class="main-nav navbar-right">
                                <li><a href="{% url 'blog:index' %}">主页</a></li>
                                <li><a href="#">关于</a></li>
                                <li><a href="#">联系我</a></li>
                            </ul>
                        </nav>
                    </div><!-- /.main-menu -->
                </div>
            </div>
        </div>
        <!-- mobile-menu-area start -->
        <div class="mobile-menu-area">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <nav id="dropdown">
                            <ul>
                                <li><a href="#">主页</a></li>
                                <li><a href="#">关于</a></li>
                                <li><a href="#">联系我</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <!-- mobile-menu-area end -->
    </div><!-- /.header-bottom -->
</header>
<!-- header-area end -->

<!-- search-area start -->
<div class="search-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="search-form">
                    <span class="search-close"></span>
                    <form action="{% url 'blog:search' %}" method="get">
                        {% csrf_token %}
                        <input type="text" name="q" placeholder="输入关键词搜索..."/>
                        <button type="submit" class="search-btn"><i class="fa fa-search"></i></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- search-area end -->

<!-- slider-area start -->

<!-- slider-area end -->

<!-- main-content-area start -->
<div id="main-content" class="main-content-area">
    <div class="container">
        <div class="row">
            {% block main %}
            {% endblock main %}
            {% block aside %}
                {% include 'blog/sidebar.html' %}
            {% endblock aside %}
        </div>
    </div>
</div>
<!-- main-content-area end -->

<!-- footer-area start -->
<footer id="footer" class="footer-area text-center">
    <p class="copyright-text">&copy; Copyright© 2015 Blogging. All right reserved.</p>
</footer>
<!-- footer-area end -->

<!-- jquery
============================================ -->
<script src="{% static 'blog/js/vendor/jquery-1.11.3.min.js' %}"></script>
<!-- bootstrap JS
============================================ -->
<script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
<!-- meanmenu JS
============================================ -->
<script src="{% static 'blog/js/jquery.meanmenu.js' %}"></script>
<!-- owl.carousel JS
============================================ -->
<script src="{% static 'blog/js/owl.carousel.min.js' %}"></script>
<!-- scrollUp JS
============================================ -->
<script src="{% static 'blog/js/jquery.scrollUp.min.js' %}"></script>
<!-- plugins JS
============================================ -->
<script src="{% static 'blog/js/plugins.js' %}"></script>
<!-- main JS
============================================ -->
<script src="{% static 'blog/js/main.js' %}"></script>
<!-- 多说公共JS代码 start (一个网页只需插入一次) -->
<script type="text/javascript">
    var duoshuoQuery = {short_name: "zmrenwu"};
    (function () {
        var ds = document.createElement('script');
        ds.type = 'text/javascript';
        ds.async = true;
        ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
        ds.charset = 'UTF-8';
        (document.getElementsByTagName('head')[0]
        || document.getElementsByTagName('body')[0]).appendChild(ds);
    })();
</script>
<!-- 多说公共JS代码 end -->
</body>
</html>