blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<year>[0-9]{4})/(?P<month>[-\w]+)/(?P<day>[0-9]+)/(?P<slug>.+)/$',
        views.PostDetailView.as_view(), name="detail"),
    url(r'^category/(?P<slug>.+)/$', views.InCategoryView.as_view(), name='in_category'),
    url(r'^tag/(?P<slug>.+)/$', views.InTagView.as_view(), name='in_tag'),
    url(r'^search/$', views.SearchView.as_view(), name='search'),
    url(r'^archive/(?P<year>[0-9]{4})/$', views.PostYearArchiveView.as_view(), name='archive_year'),
    url(r'^archive/(?P<year>[0-9]{4})/(?P<month>[0-9]+)/$', views.PostMonthArchiveView.as_view(),
        name="archive_month"),
    # url(r'^messages/$', views.MessageBoardView.as_view(), name='message_board'),
    # url(r'^messages/(?P<slug>.+)/$', views.AnnouncementDetailView.as_view(), name='announcement'),
    # url(r'^contact/$', views.ContactView.as_view(), name='contact'),
]

comments/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^reply/(?P<pid>[0-9]+)$',
        view=views.CommentReplyView.as_view(),
        name='reply'
    ),
    url(r'^success/$',
        views.CommentSuccess.as_view(),
        name='comment_success'),
]

config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap

from blog.models import Post

info_dict = {
    'queryset': Post.objects.all(),
    'date_field': 'modified',
}


urlpatterns = [
    url(r'', include('blog.urls', namespace='blog')),
    url(r'^admin/', admin.site.urls),
    url(r'^comment/', include('django_comments.urls')),
    url(r'^comment/', include('comments.urls', namespace='comments')),
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'blog': GenericSitemap(info_dict, priority=0.6)}},
        name='django.contrib.sitemaps.views.sitemap'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/models.py
import re

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.html import mark_safe, escape

from django_comments.abstracts import CommentAbstractModel
from django_comments.managers import CommentManager
from mptt.models import MPTTModel, TreeForeignKey
from mptt.managers import TreeManager
from markdownx.utils import markdownify


class MyCommentManager(TreeManager, CommentManager):
    pass


class MyComment(MPTTModel, CommentAbstractModel):
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', verbose_name=_('parent comment'))
    follow = models.BooleanField(_('follow up'), default=True)

    objects = MyCommentManager()

    class Meta(CommentAbstractModel.Meta):
        pass

    class MPTTMeta:
        order_insertion_by = ['-submit_date']

    def get_descendants_reversely(self):
        return self.get_descendants().order_by('submit_date')

    @property
    def comment_html(self):
        return markdownify(self.comment)

comments/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from django_comments.forms import CommentForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Hidden, Submit

from . import get_model

import django_comments


class MyCommentForm(CommentForm):
    parent = forms.IntegerField(required=False, widget=forms.HiddenInput)

    def __init__(self, target_object, parent=None, data=None, initial=None, **kwargs):
        self.parent = parent
        if initial is None:
            initial = {}
        initial.update({'parent': self.parent})
        super(MyCommentForm, self).__init__(target_object, data=data, initial=initial, **kwargs)

        self.helper = FormHelper(self)
        self.helper.form_action = django_comments.get_form_target()
        self.helper.layout = Layout(
            Div(
                'honeypot',
                'parent',
                'content_type',
                'object_pk',
                'timestamp',
                'security_hash',
                Hidden('next', '{% url "comments:comment_success" %}'),
                Div(
                    'name', css_class='col-md-4'
                ),
                Div(
                    'email', css_class='col-md-4'
                ),
                Div(
                    'url', css_class='col-md-4'
                ),
                Div(
                    'comment', css_class='col-md-12'
                ),
                css_class='row'
            )
        )
        self.helper.add_input(Submit('submit', '发表评论', css_class='btn-sm pull-xs-right'))
        self.fields['comment'].widget.attrs['rows'] = 6
        self.fields['comment'].label = '评论'
        self.fields['name'].label = '名字'
        self.fields['url'].label = '网址'

    def get_comment_model(self):
        return get_model()

    def get_comment_create_data(self):
        d = super(MyCommentForm, self).get_comment_create_data()
        d['parent_id'] = self.cleaned_data['parent']
        return d

comments/views.py
from django.views.generic import View, DetailView, RedirectView
from django.views.generic.edit import FormMixin
from django.core.exceptions import ObjectDoesNotExist

from .models import MyComment
from .forms import MyCommentForm

import django_comments as comments


class CommentReplyView(FormMixin, DetailView):
    model = MyComment
    form_class = MyCommentForm
    pk_url_kwarg = 'pid'
    template_name = 'comments/reply.html'

    def get_form_kwargs(self):
        kwargs = super(CommentReplyView, self).get_form_kwargs()
        kwargs.update({
            'target_object': self.object.content_object,
            'parent': self.object.pk
        })
        return kwargs


# TODO: fix redirect action very slow in production
class CommentSuccess(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        self.url = self.comment.get_absolute_url()
        return super(CommentSuccess, self).get_redirect_url(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        self.comment = None
        if 'c' in request.GET:
            try:
                self.comment = comments.get_model().objects.get(
                    pk=request.GET['c'])
            except (ObjectDoesNotExist, ValueError):
                pass
        if self.comment and self.comment.is_public:
            return super(CommentSuccess, self).get(request, *args, **kwargs)

# class CommentSuccess(TemplateResponseMixin, View):
#     template_name = 'comments/posted.html'
#
#     def get_context_data(self, **kwargs):
#         return {'comment': self.comment}
#
#     def get(self, request, *args, **kwargs):
#         self.comment = None
#
#         if 'c' in request.GET:
#             try:
#                 self.comment = comments.get_model().objects.get(
#                     pk=request.GET['c'])
#             except (ObjectDoesNotExist, ValueError):
#                 pass
#         if self.comment and self.comment.is_public:
#             return HttpResponsePermanentRedirect(
#                 self.comment.get_absolute_url())
#
#         context = self.get_context_data(**kwargs)
#         return self.render_to_response(context)

templates/comments/form.html
{% load crispy_forms_tags %}

{% crispy form %}
{#    <form action="">#}
{#        <div class="row">#}
{#            <div class="col-md-4">#}
{#                <div class="form-group">#}
{#                    <label for="exampleInputEmail1">昵称：</label>#}
{#                    <input type="email" class="form-control" id="exampleInputEmail1"#}
{#                           aria-describedby="emailHelp" placeholder="">#}
{#                </div>#}
{#            </div>#}
{#            <div class="col-md-4">#}
{#                <div class="form-group">#}
{#                    <label for="exampleInputEmail1">邮箱：</label>#}
{#                    <input type="email" class="form-control" id="exampleInputEmail1"#}
{#                           aria-describedby="emailHelp" placeholder="">#}
{#                </div>#}
{#            </div>#}
{#            <div class="col-md-4">#}
{#                <div class="form-group">#}
{#                    <label for="exampleInputEmail1">网址：</label>#}
{#                    <input type="email" class="form-control" id="exampleInputEmail1"#}
{#                           aria-describedby="emailHelp" placeholder="">#}
{#                </div>#}
{#            </div>#}
{#            <div class="col-md-12">#}
{#                <div class="form-group">#}
{#                    <textarea class="form-control" id="exampleTextarea" rows="5"></textarea>#}
{#                </div>#}
{#            </div>#}
{#            <div class="col-md-12">#}
{#                <button class="btn btn-outline-primary btn-sm pull-xs-right">发表评论</button>#}
{#            </div>#}
{#        </div>#}
{#    </form>#}

templates/comments/list.html
{% load staticfiles comments bleach_tags %}
<div class="card card-block">
    {% render_comment_form for post %}
</div>
<div class="card card-block" id="comment-panel">
    {% get_comment_count for post as comment_count %}
    <h3 class="card-title">评论列表
        <small>({{ comment_count }})</small>
    </h3>
    <hr>
    {% if comment_count %}
        <ul class="media-list">
            {% for root_comment in post.root_comments %}
                <li class="media" id="c{{ root_comment.pk }}">
                    <div class="media-left">
                        <a href="#">
                            <img class="media-object" src="{% static 'blog/images/default_avatar.jpg' %}"
                                 alt="Generic placeholder image"
                                 style="width: 34px">
                        </a>
                    </div>
                    <div class="media-body">
                        <ul class="list-inline comment-meta">
                            <li class="list-inline-item">
                                <span class="media-heading font-weight-bold">
                                    {{ root_comment.name }}
                                    {% if root_comment.user.is_superuser %}
                                        <span class="tag tag-info">博主</span>
                                    {% endif %}
                                </span>
                            </li>
                            <li class="list-inline-item">
                                <time class="text-muted"
                                      title="{{ root_comment.submit_date }}">{{ root_comment.submit_date |timesince }}前
                                </time>
                            </li>
                            <li class="list-inline-item">
                                <a href="{% url 'comments:reply' root_comment.pk %}">回复</a>
                            </li>
                        </ul>
                        <div class="card-text">{{ root_comment.comment_html|bleach|safe }}</div>

                        <!-- Nested media object -->
                        {% for desc_comment in root_comment.get_descendants_reversely %}
                            <div class="media" id="c{{ desc_comment.pk }}">
                                <a class="media-left" href="#">
                                    <img class="media-object" src="{% static 'blog/images/default_avatar.jpg' %}"
                                         alt="Generic placeholder image"
                                         style="width: 34px">
                                </a>
                                <div class="media-body">
                                    <ul class="list-inline comment-meta">
                                        <li class="list-inline-item">
                                            <span class="media-heading font-weight-bold">{{ desc_comment.name }}
                                                {% if desc_comment.user.is_superuser %}
                                                    <span class="tag tag-info">博主</span>
                                                {% endif %}
                                            </span>
                                            <i class="fa fa-share" aria-hidden="true"></i>
                                            <span class="media-heading font-weight-bold">{{ desc_comment.parent.name }}
                                                {% if desc_comment.parent.user.is_superuser %}
                                                    <span class="tag tag-info">博主</span>
                                                {% endif %}</span>
                                        </li>
                                        <li class="list-inline-item">
                                            <time class="text-muted"
                                                  title="{{ desc_comment.submit_date }}">{{ desc_comment.submit_date |timesince }}前
                                            </time>
                                        </li>
                                        <li class="list-inline-item">
                                            <a href="{% url 'comments:reply' desc_comment.pk %}">回复</a>
                                        </li>
                                    </ul>
                                    <div class="card-text">{{ desc_comment.comment_html|bleach|safe }}</div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </li>
                <br>
            {% endfor %}
        </ul>
    {% else %}
        <div>暂无评论</div>
    {% endif %}
</div>

templates/comments/reply.html
{% extends 'base.html' %}
{% load staticfiles comments crispy_forms_tags bleach_tags %}
{% block main %}
    <div class="col-md-8">
        <h4 class="m-b-1 alert mark">回复<span class="font-weight-bold"> {{ mycomment.name }} </span>的评论：</h4>
        <div class="card card-block">
            <div class="media">
                <div class="media-left">
                    <a href="#">
                        <img class="media-object" src="{% static 'blog/images/default_avatar.jpg' %}"
                             alt="Generic placeholder image"
                             style="width: 34px">
                    </a>
                </div>
                <div class="media-body">
                    <ul class="list-inline comment-meta">
                        <li class="list-inline-item">
                            <span class="media-heading font-weight-bold">{{ mycomment.name }}</span>
                        </li>
                        <li class="list-inline-item">
                            <time class="text-muted">{{ mycomment.submit_date |timesince }}前</time>
                        </li>
                    </ul>
                    <p class="card-text">{{ mycomment.comment_html|bleach|safe }}</p>
                    <hr>
                    {% crispy form %}
                </div>
            </div>
        </div>
    </div>
{% endblock main %}